import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/navbar";
import { Toaster } from "react-hot-toast";
import { ClerkProvider } from "@clerk/nextjs";
import { Sidebar } from "@/components/sidebar";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/providers/theme-providers";
import NextBreadcrumb from "@/components/bread-crumb";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <ThemeProvider>
            <NavBar />
            {/* because navbar is in fixed position, we should add padding top on every page ,
            we can add common style here for every page*/}

            <Sidebar />

            <Toaster />
            <main className="md:pl-56 pt-16 h-full">
              <NextBreadcrumb
                homeElement={"Home"}
                separator={<span> / </span>}
                activeClasses="text-slate-500"
                // containerClasses="bg-gradient-to-r from-purple-600 to-blue-600"
              />
              {children}
            </main>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
